-- Lua 5.3 Runtime Capture for Luraph VM with bit32 extensions
-- This adds missing bit32 functions then captures bytecode at runtime

-- Wrap string.pack to handle unsigned overflow (convert negative to unsigned)
local original_string_pack = string.pack
string.pack = function(fmt, ...)
    local args = {...}

    -- Force all numeric arguments to unsigned range if they're negative
    for i, v in ipairs(args) do
        if type(v) == "number" and v < 0 then
            -- Convert negative to unsigned 32-bit
            args[i] = v % (2^32)
        elseif type(v) == "number" and v > 2^31 then
            -- Already large positive, might need to modulo for smaller types
            -- Keep as is, the format will handle it
        end
    end

    -- Use pcall to catch and handle errors
    local ok, result = pcall(original_string_pack, fmt, table.unpack(args))
    if ok then
        return result
    else
        -- If still failing, try forcing all numbers to proper unsigned values
        for i, v in ipairs(args) do
            if type(v) == "number" then
                if v < 0 then
                    args[i] = (v % (2^32)) & 0xFFFFFFFF
                elseif v > 0xFFFFFFFF then
                    args[i] = v & 0xFFFFFFFF
                end
            end
        end
        local ok2, result2 = pcall(original_string_pack, fmt, table.unpack(args))
        if ok2 then
            return result2
        else
            error(result .. " (fmt=" .. fmt .. ")")
        end
    end
end

-- Add missing bit32 functions (countlz and countrz are Luau-specific)
bit32.countlz = function(a)
    a = (a or 0) & 0xFFFFFFFF
    if a == 0 then return 32 end
    local n = 0
    if a <= 0x0000FFFF then n = n + 16; a = a << 16 end
    if a <= 0x00FFFFFF then n = n + 8; a = a << 8 end
    if a <= 0x0FFFFFFF then n = n + 4; a = a << 4 end
    if a <= 0x3FFFFFFF then n = n + 2; a = a << 2 end
    if a <= 0x7FFFFFFF then n = n + 1 end
    return n
end

bit32.countrz = function(a)
    a = (a or 0) & 0xFFFFFFFF
    if a == 0 then return 32 end
    local n = 0
    if (a & 0x0000FFFF) == 0 then n = n + 16; a = a >> 16 end
    if (a & 0x000000FF) == 0 then n = n + 8; a = a >> 8 end
    if (a & 0x0000000F) == 0 then n = n + 4; a = a >> 4 end
    if (a & 0x00000003) == 0 then n = n + 2; a = a >> 2 end
    if (a & 0x00000001) == 0 then n = n + 1 end
    return n
end

print("-- bit32 extensions added (countlz, countrz)")

-- Load the VM
local VM = dofile("/home/user/deobluraph/deobfuscated_lua54.lua")

local function log(msg)
    print(msg)
end

log("-- ============================================")
log("-- LURAPH RUNTIME BYTECODE CAPTURE (Lua 5.3)")
log("-- ============================================")
log("")

-- Function counter
local func_count = 0
local max_funcs = 100

-- Output file for captured data
local outfile = io.open("/home/user/deobluraph/captured_runtime.lua", "w")
outfile:write("-- Captured runtime bytecode from Luraph VM\n")
outfile:write("-- Generated by lua53_runtime_capture.lua\n\n")
outfile:write("local captured = {\n")

local function write_array(arr, name, max_len)
    max_len = max_len or 3000
    if type(arr) ~= "table" then
        outfile:write(string.format("  %s = %s,\n", name, tostring(arr)))
        return
    end

    local len = 0
    local indices = {}
    for k in pairs(arr) do
        len = len + 1
        if type(k) == "number" then
            table.insert(indices, k)
        end
    end
    table.sort(indices)

    outfile:write(string.format("  %s = { -- %d entries\n", name, len))

    local written = 0
    for _, i in ipairs(indices) do
        if written >= max_len then break end
        local v = arr[i]
        if v ~= nil then
            if type(v) == "string" then
                local s = v
                if #s > 80 then s = string.sub(s, 1, 80) .. "..." end
                s = string.gsub(s, "\\", "\\\\")
                s = string.gsub(s, "\n", "\\n")
                s = string.gsub(s, "\r", "\\r")
                s = string.gsub(s, '"', '\\"')
                s = string.gsub(s, "[%c]", function(c)
                    return string.format("\\x%02X", string.byte(c))
                end)
                outfile:write(string.format('    [%d] = "%s",\n', i, s))
            elseif type(v) == "number" then
                outfile:write(string.format("    [%d] = %s,\n", i, tostring(v)))
            elseif type(v) == "boolean" then
                outfile:write(string.format("    [%d] = %s,\n", i, tostring(v)))
            end
            written = written + 1
        end
    end

    if len > max_len then
        outfile:write(string.format("    -- ... %d more entries truncated\n", len - max_len))
    end
    outfile:write("  },\n")
end

-- Check if VM is defined
if not VM or type(VM) ~= "table" then
    log("-- ERROR: VM not defined or not a table")
    return
end

log("-- VM table loaded successfully")

local vm_count = 0
for k, v in pairs(VM) do
    vm_count = vm_count + 1
end
log("-- VM has " .. vm_count .. " entries")

-- Find E8 (main interpreter setup function)
local E8 = VM.E8
if not E8 then
    log("-- ERROR: E8 function not found")
    return
end

log("-- Found E8 function")
log("-- Installing bytecode capture hooks...")

-- Hook E8
VM.E8 = function(z, V, B, L)
    log("-- [HOOK] E8 called")
    E8(z, V, B, L)

    local interp = V[40] or V[0x28]
    if interp and type(interp) == "function" then
        log("-- [HOOK] Found interpreter at V[40]")
        local orig_interp = interp

        V[40] = function(W, y, I)
            func_count = func_count + 1
            local fid = func_count

            if fid <= max_funcs then
                log("-- FUNCTION " .. fid)

                outfile:write(string.format("\n  -- Function %d\n", fid))
                outfile:write(string.format("  func_%d = {\n", fid))

                if type(W) == "table" then
                    -- W[10] = instructions (opcodes)
                    -- W[11] = strings
                    -- W[9] = constants
                    -- W[4] = operand A
                    -- W[5] = operand C
                    -- W[7] = operand B
                    -- W[8] = constants (numbers)

                    if type(W[10]) == "table" then
                        local cnt = 0
                        for _ in pairs(W[10]) do cnt = cnt + 1 end
                        log("--   instructions: " .. cnt)
                        outfile:write("    instructions = {\n")
                        local count = 0
                        for i = 1, 10000 do
                            if W[10][i] ~= nil then
                                outfile:write(string.format("      [%d] = %s,\n", i, tostring(W[10][i])))
                                count = count + 1
                                if count >= 2000 then break end
                            elseif count > 0 and i > count + 10 then
                                break
                            end
                        end
                        outfile:write("    },\n")
                    end

                    if type(W[11]) == "table" then
                        local cnt = 0
                        for _ in pairs(W[11]) do cnt = cnt + 1 end
                        log("--   strings: " .. cnt)
                        outfile:write("    strings = {\n")
                        local count = 0
                        for i = 1, 1000 do
                            if W[11][i] ~= nil then
                                local s = tostring(W[11][i])
                                if #s > 100 then s = string.sub(s, 1, 100) .. "..." end
                                s = string.gsub(s, "\\", "\\\\")
                                s = string.gsub(s, "\n", "\\n")
                                s = string.gsub(s, "\r", "\\r")
                                s = string.gsub(s, '"', '\\"')
                                s = string.gsub(s, "[%c]", function(c)
                                    return string.format("\\x%02X", string.byte(c))
                                end)
                                outfile:write(string.format('      [%d] = "%s",\n', i, s))
                                count = count + 1
                                if count >= 500 then break end
                            elseif count > 0 and i > count + 10 then
                                break
                            end
                        end
                        outfile:write("    },\n")
                    end

                    if type(W[9]) == "table" then
                        local cnt = 0
                        for _ in pairs(W[9]) do cnt = cnt + 1 end
                        log("--   constants: " .. cnt)
                        outfile:write("    constants = {\n")
                        local count = 0
                        for i = 1, 1000 do
                            if W[9][i] ~= nil then
                                local v = W[9][i]
                                if type(v) == "string" then
                                    local s = v
                                    if #s > 100 then s = string.sub(s, 1, 100) .. "..." end
                                    s = string.gsub(s, "\\", "\\\\")
                                    s = string.gsub(s, "\n", "\\n")
                                    s = string.gsub(s, "\r", "\\r")
                                    s = string.gsub(s, '"', '\\"')
                                    outfile:write(string.format('      [%d] = "%s",\n', i, s))
                                else
                                    outfile:write(string.format("      [%d] = %s,\n", i, tostring(v)))
                                end
                                count = count + 1
                                if count >= 500 then break end
                            elseif count > 0 and i > count + 10 then
                                break
                            end
                        end
                        outfile:write("    },\n")
                    end

                    -- Operand arrays
                    for idx, name in pairs({[4]="operandA", [5]="operandC", [7]="operandB"}) do
                        if type(W[idx]) == "table" then
                            local cnt = 0
                            for _ in pairs(W[idx]) do cnt = cnt + 1 end
                            log("--   " .. name .. ": " .. cnt)
                            outfile:write(string.format("    %s = {\n", name))
                            local count = 0
                            for i = 1, 10000 do
                                if W[idx][i] ~= nil then
                                    outfile:write(string.format("      [%d] = %s,\n", i, tostring(W[idx][i])))
                                    count = count + 1
                                    if count >= 2000 then break end
                                elseif count > 0 and i > count + 10 then
                                    break
                                end
                            end
                            outfile:write("    },\n")
                        end
                    end
                end

                outfile:write("  },\n")
                outfile:flush()
            end

            return orig_interp(W, y, I)
        end

        V[0x28] = V[40]
        log("-- [HOOK] Interpreter hook installed")
    end
end

log("")
log("-- Looking for entry point...")

local wS = VM.wS
if wS then
    log("-- Found wS, executing...")
    local ok, err = pcall(function() VM:wS() end)
    if ok then
        log("-- Execution completed normally")
    else
        log("-- Execution error: " .. tostring(err))
    end
else
    log("-- wS not found, available functions:")
    for k, v in pairs(VM) do
        if type(v) == "function" and type(k) == "string" then
            log("  " .. k)
        end
    end
end

outfile:write("}\n\nreturn captured\n")
outfile:close()

log("")
log("-- ============================================")
log("-- CAPTURE COMPLETE")
log("-- ============================================")
log("-- Functions captured: " .. func_count)
log("-- Output written to: captured_runtime.lua")
