-- LuaJIT Runtime Capture for Luraph VM
-- LuaJIT has better compatibility with Luau-style code

-- Create bit32 compatibility layer using LuaJIT's bit library
local bit = require("bit")
bit32 = {
    band = bit.band,
    bor = bit.bor,
    bxor = bit.bxor,
    bnot = bit.bnot,
    lshift = bit.lshift,
    rshift = bit.rshift,
    arshift = bit.arshift,
    lrotate = bit.rol,
    rrotate = bit.ror,
    btest = function(a, b)
        return bit.band(a, b) ~= 0
    end,
    extract = function(n, field, width)
        width = width or 1
        return bit.band(bit.rshift(n, field), bit.lshift(1, width) - 1)
    end,
    replace = function(n, v, field, width)
        width = width or 1
        local mask = bit.lshift(1, width) - 1
        return bit.bor(bit.band(n, bit.bnot(bit.lshift(mask, field))),
                       bit.lshift(bit.band(v, mask), field))
    end,
    countlz = function(a)
        a = bit.band(a or 0, 0xFFFFFFFF)
        if a == 0 then return 32 end
        local n = 0
        if bit.band(a, 0xFFFF0000) == 0 then n = n + 16; a = bit.lshift(a, 16) end
        if bit.band(a, 0xFF000000) == 0 then n = n + 8; a = bit.lshift(a, 8) end
        if bit.band(a, 0xF0000000) == 0 then n = n + 4; a = bit.lshift(a, 4) end
        if bit.band(a, 0xC0000000) == 0 then n = n + 2; a = bit.lshift(a, 2) end
        if bit.band(a, 0x80000000) == 0 then n = n + 1 end
        return n
    end,
    countrz = function(a)
        a = bit.band(a or 0, 0xFFFFFFFF)
        if a == 0 then return 32 end
        local n = 0
        if bit.band(a, 0x0000FFFF) == 0 then n = n + 16; a = bit.rshift(a, 16) end
        if bit.band(a, 0x000000FF) == 0 then n = n + 8; a = bit.rshift(a, 8) end
        if bit.band(a, 0x0000000F) == 0 then n = n + 4; a = bit.rshift(a, 4) end
        if bit.band(a, 0x00000003) == 0 then n = n + 2; a = bit.rshift(a, 2) end
        if bit.band(a, 0x00000001) == 0 then n = n + 1 end
        return n
    end
}

print("-- bit32 compatibility layer installed")

-- table.move compatibility (Lua 5.3+)
if not table.move then
    table.move = function(a1, f, e, t, a2)
        a2 = a2 or a1
        if t <= f or a1 ~= a2 then
            for i = f, e do
                a2[t + (i - f)] = a1[i]
            end
        else
            for i = e, f, -1 do
                a2[t + (i - f)] = a1[i]
            end
        end
        return a2
    end
end

-- unpack compatibility
if not unpack then
    unpack = table.unpack
end

print("-- Loading VM...")

-- Load the VM (standard lua version)
local VM = dofile("/home/user/deobluraph/deobfuscated_standard.lua")

local function log(msg)
    print(msg)
end

log("")
log("-- ============================================")
log("-- LURAPH RUNTIME BYTECODE CAPTURE (LuaJIT)")
log("-- ============================================")
log("")

-- Function counter
local func_count = 0
local max_funcs = 100

-- Output file
local outfile = io.open("/home/user/deobluraph/captured_luajit.lua", "w")
outfile:write("-- Captured runtime bytecode from Luraph VM (LuaJIT)\n")
outfile:write("-- Generated by luajit_capture.lua\n\n")
outfile:write("local captured = {\n")

-- Check if VM is defined
if not VM or type(VM) ~= "table" then
    log("-- ERROR: VM not defined or not a table")
    return
end

log("-- VM table loaded successfully")

local vm_count = 0
for k, v in pairs(VM) do
    vm_count = vm_count + 1
end
log("-- VM has " .. vm_count .. " entries")

-- Find E8 (main interpreter setup function)
local E8 = VM.E8
if not E8 then
    log("-- ERROR: E8 function not found")
    log("-- Available functions:")
    for k, v in pairs(VM) do
        if type(v) == "function" and type(k) == "string" then
            log("  " .. k)
        end
    end
    return
end

log("-- Found E8 function")
log("-- Installing bytecode capture hooks...")

-- Hook E8
VM.E8 = function(z, V, B, L)
    log("-- [HOOK] E8 called")
    E8(z, V, B, L)

    local interp = V[40] or V[0x28]
    if interp and type(interp) == "function" then
        log("-- [HOOK] Found interpreter at V[40]")
        local orig_interp = interp

        V[40] = function(W, y, I)
            func_count = func_count + 1
            local fid = func_count

            if fid <= max_funcs then
                log("-- FUNCTION " .. fid)

                outfile:write(string.format("\n  func_%d = {\n", fid))

                if type(W) == "table" then
                    -- Dump instructions
                    if type(W[10]) == "table" then
                        local cnt = 0
                        for _ in pairs(W[10]) do cnt = cnt + 1 end
                        log("--   instructions: " .. cnt)
                        outfile:write("    instructions = {\n")
                        local count = 0
                        for i = 1, 10000 do
                            if W[10][i] ~= nil then
                                outfile:write(string.format("      [%d] = %s,\n", i, tostring(W[10][i])))
                                count = count + 1
                                if count >= 2000 then break end
                            elseif count > 0 and i > count + 10 then
                                break
                            end
                        end
                        outfile:write("    },\n")
                    end

                    -- Dump strings
                    if type(W[11]) == "table" then
                        local cnt = 0
                        for _ in pairs(W[11]) do cnt = cnt + 1 end
                        log("--   strings: " .. cnt)
                        outfile:write("    strings = {\n")
                        local count = 0
                        for i = 1, 1000 do
                            if W[11][i] ~= nil then
                                local s = tostring(W[11][i])
                                if #s > 100 then s = string.sub(s, 1, 100) .. "..." end
                                s = string.gsub(s, "\\", "\\\\")
                                s = string.gsub(s, "\n", "\\n")
                                s = string.gsub(s, "\r", "\\r")
                                s = string.gsub(s, '"', '\\"')
                                s = string.gsub(s, "[%c]", function(c)
                                    return string.format("\\x%02X", string.byte(c))
                                end)
                                outfile:write(string.format('      [%d] = "%s",\n', i, s))
                                count = count + 1
                                if count >= 500 then break end
                            elseif count > 0 and i > count + 10 then
                                break
                            end
                        end
                        outfile:write("    },\n")
                    end

                    -- Dump constants
                    if type(W[9]) == "table" then
                        local cnt = 0
                        for _ in pairs(W[9]) do cnt = cnt + 1 end
                        log("--   constants: " .. cnt)
                        outfile:write("    constants = {\n")
                        local count = 0
                        for i = 1, 1000 do
                            if W[9][i] ~= nil then
                                local v = W[9][i]
                                if type(v) == "string" then
                                    local s = v
                                    if #s > 100 then s = string.sub(s, 1, 100) .. "..." end
                                    s = string.gsub(s, "\\", "\\\\")
                                    s = string.gsub(s, "\n", "\\n")
                                    s = string.gsub(s, "\r", "\\r")
                                    s = string.gsub(s, '"', '\\"')
                                    outfile:write(string.format('      [%d] = "%s",\n', i, s))
                                else
                                    outfile:write(string.format("      [%d] = %s,\n", i, tostring(v)))
                                end
                                count = count + 1
                                if count >= 500 then break end
                            elseif count > 0 and i > count + 10 then
                                break
                            end
                        end
                        outfile:write("    },\n")
                    end

                    -- Operand arrays
                    for idx, name in pairs({[4]="operandA", [5]="operandC", [7]="operandB"}) do
                        if type(W[idx]) == "table" then
                            local cnt = 0
                            for _ in pairs(W[idx]) do cnt = cnt + 1 end
                            log("--   " .. name .. ": " .. cnt)
                            outfile:write(string.format("    %s = {\n", name))
                            local count = 0
                            for i = 1, 10000 do
                                if W[idx][i] ~= nil then
                                    outfile:write(string.format("      [%d] = %s,\n", i, tostring(W[idx][i])))
                                    count = count + 1
                                    if count >= 2000 then break end
                                elseif count > 0 and i > count + 10 then
                                    break
                                end
                            end
                            outfile:write("    },\n")
                        end
                    end
                end

                outfile:write("  },\n")
                outfile:flush()
            end

            return orig_interp(W, y, I)
        end

        V[0x28] = V[40]
        log("-- [HOOK] Interpreter hook installed")
    end
end

log("")
log("-- Looking for entry point...")

local wS = VM.wS
if wS then
    log("-- Found wS, executing VM...")
    local ok, err = pcall(function() VM:wS() end)
    if ok then
        log("-- Execution completed normally")
    else
        log("-- Execution error: " .. tostring(err))
    end
else
    log("-- wS not found")
end

outfile:write("}\n\nreturn captured\n")
outfile:close()

log("")
log("-- ============================================")
log("-- CAPTURE COMPLETE")
log("-- ============================================")
log("-- Functions captured: " .. func_count)
log("-- Output written to: captured_luajit.lua")
